# Generated by Django 5.0.14 on 2026-02-22 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('name', models.CharField(max_length=100, verbose_name='동아리명')),
                ('description', models.TextField(blank=True, default='', verbose_name='설명')),
                ('logo_url', models.URLField(blank=True, default='', verbose_name='로고 URL')),
                ('phase', models.CharField(choices=[('RECRUITING', '모집 중'), ('SELECTED', '선발 완료'), ('OPERATING', '운영 중'), ('COMPLETED', '완료')], default='OPERATING', max_length=20, verbose_name='단계')),
            ],
            options={
                'verbose_name': '동아리',
                'verbose_name_plural': '동아리',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEADER', '리더'), ('MEMBER', '멤버')], default='MEMBER', max_length=10, verbose_name='멤버 역할')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일시')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clubs.club', verbose_name='동아리')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '동아리 멤버',
                'verbose_name_plural': '동아리 멤버',
                'ordering': ['-joined_at'],
                'unique_together': {('club', 'user')},
            },
        ),
    ]
