# Generated by Django 5.0.14 on 2026-02-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="logo_url",
        ),
        migrations.AddField(
            model_name="club",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="clubs/logos/", verbose_name="로고"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="활성 여부"
            ),
        ),
    ]
