# Generated by Django 5.0.14 on 2026-02-22 07:31

import apps.files.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('file', models.FileField(upload_to=apps.files.models.upload_to, verbose_name='파일')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('size', models.PositiveIntegerField(verbose_name='파일 크기 (bytes)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME 타입')),
                ('category', models.CharField(choices=[('RECEIPT', '영수증'), ('REPORT', '보고서'), ('INSPECTION', '점검'), ('ACHIEVEMENT', '성과물'), ('GENERAL', '일반')], default='GENERAL', max_length=20, verbose_name='카테고리')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clubs.club', verbose_name='동아리')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'verbose_name': '업로드 파일',
                'verbose_name_plural': '업로드 파일',
                'ordering': ['-created_at'],
            },
        ),
    ]
